import { ChevronLeft, ChevronRight, PenLine } from "lucide-react";
import { useState } from "react";
import { calendarDays, monthTitle, todayKey } from "../lib/dates";
import { moodFor, moodStats, writingStreak } from "../lib/moods";
import type { DiaryEntry } from "../lib/types";

export function CalendarView({ entries, onDay }: { entries: DiaryEntry[]; onDay: (date: string, entry?: DiaryEntry) => void }) {
  const [month, setMonth] = useState(() => new Date());
  const days = calendarDays(month);
  const stats = moodStats(entries, month);
  return <section className="calendar-view"><div className="calendar-heading"><div><span className="eyebrow">A gentler way to notice</span><h1>Calendar</h1><p>Every page counts, even the small ones.</p></div><div className="month-switcher"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label="Previous month"><ChevronLeft size={18} /></button><strong>{monthTitle(month)}</strong><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label="Next month"><ChevronRight size={18} /></button></div></div><div className="calendar-card"><div className="weekday-row">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{days.map((day) => { const key = todayKey(day); const entry = entries.find((item) => item.date === key); const inMonth = day.getMonth() === month.getMonth(); return <button key={key} className={!inMonth ? "outside-month" : ""} type="button" onClick={() => onDay(key, entry)}><span>{day.getDate()}</span>{entry && <i style={{ background: moodFor(entry.mood).color }} title={moodFor(entry.mood).label} />}</button>; })}</div></div><div className="mood-map"><div className="mood-map-heading"><div><span className="eyebrow">Mood map</span><h2>{stats.primary ? `Mostly ${stats.primary.label.toLowerCase()} this month` : "Your month is still unfolding"}</h2></div><PenLine size={20} /></div><div className="mood-bars">{stats.counts.map((mood) => <span key={mood.id} style={{ width: `${stats.total ? Math.max(3, (mood.count / stats.total) * 100) : 3}%`, background: mood.color }} title={`${mood.label}: ${mood.count}`} />)}</div><div className="mood-legend">{stats.counts.filter((mood) => mood.count).map((mood) => <span key={mood.id}><i style={{ background: mood.color }} />{mood.label} {mood.count}</span>)}</div></div><p className="streak-copy">{writingStreak(entries) > 1 ? `${writingStreak(entries)} days in a row` : "No pressure, just your own rhythm"}</p></section>;
}