import { useMemo, useState } from "react";
import { Heart, Search, X } from "lucide-react";
import { EntryCard, NewEntryCard } from "./EntryCard";
import type { DiaryEntry } from "../lib/types";

type JournalGridProps = { entries: DiaryEntry[]; ownerName: string; dedication: string; onNew: () => void; onOpen: (entry: DiaryEntry) => void; onFavorite: (id: string) => void; onDuplicate: (id: string) => void; onDelete: (id: string) => void; onRestore: (entry: DiaryEntry) => void };

export function JournalGrid({ entries, ownerName, dedication, onNew, onOpen, onFavorite, onDuplicate, onDelete, onRestore }: JournalGridProps) {
  const [filter, setFilter] = useState<"all" | "favorites">("all");
  const [search, setSearch] = useState("");
  const [menu, setMenu] = useState<{ entry: DiaryEntry; x: number; y: number } | null>(null);
  const [undo, setUndo] = useState<DiaryEntry | null>(null);
  const visible = useMemo(() => entries.filter((entry) => (filter === "all" || entry.favorite) && `${entry.title} ${entry.content}`.toLowerCase().includes(search.toLowerCase())), [entries, filter, search]);
  const greeting = new Intl.DateTimeFormat(undefined, { hour: "numeric" }).format(new Date()).toLowerCase().includes("pm") ? "Good evening" : "Good morning";
  const deleteWithUndo = (entry: DiaryEntry) => { setUndo(entry); onDelete(entry.id); window.setTimeout(() => setUndo(null), 4000); };
  return <section className="journal-home" onClick={() => setMenu(null)}><div className="journal-heading"><div><span className="eyebrow">Your private pages</span><h1>Journal</h1><p className="handwritten">{greeting}, {ownerName}</p></div><button className="round-add" type="button" onClick={onNew} aria-label="New entry"><span>+</span></button></div><div className="journal-tools"><label className="search-box"><Search size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search your pages" /></label><div className="segmented" role="tablist"><button className={filter === "all" ? "is-active" : ""} type="button" onClick={() => setFilter("all")}>All</button><button className={filter === "favorites" ? "is-active" : ""} type="button" onClick={() => setFilter("favorites")}><Heart size={14} /> Favourites</button></div></div>{visible.length === 0 && !search && filter === "all" ? <div className="empty-state"><div className="empty-paper"><span className="empty-rule" /><span className="empty-rule short" /><span className="empty-rule" /></div><h2>A soft place to land.</h2><p>{dedication}</p><button className="text-button" type="button" onClick={onNew}>Write your first page <span>→</span></button></div> : <div className="entry-grid"><NewEntryCard onClick={onNew} />{visible.map((entry) => <EntryCard key={entry.id} entry={entry} onClick={() => onOpen(entry)} onMenu={(event) => { event.preventDefault(); event.stopPropagation(); setMenu({ entry, x: Math.min(event.clientX, window.innerWidth - 190), y: Math.min(event.clientY, window.innerHeight - 170) }); }} />)}</div>}{menu && <div className="context-menu" style={{ left: menu.x, top: menu.y }} onClick={(event) => event.stopPropagation()}><strong>{menu.entry.title || "This page"}</strong><button type="button" onClick={() => { onFavorite(menu.entry.id); setMenu(null); }}><Heart size={15} /> {menu.entry.favorite ? "Remove favourite" : "Favourite"}</button><button type="button" onClick={() => { onDuplicate(menu.entry.id); setMenu(null); }}>Duplicate</button><button className="danger-text" type="button" onClick={() => { deleteWithUndo(menu.entry); setMenu(null); }}>Delete</button></div>}{undo && <div className="undo-toast"><span>Page deleted</span><button type="button" onClick={() => { onRestore(undo); setUndo(null); }}>Undo</button><X size={15} onClick={() => setUndo(null)} /></div>}</section>;
}